## Aliases
alias a='alias'
alias c='clear'
alias clock='tty-clock -c -t -D -B'
alias dell='ssh admin@192.168.1.28'
alias e='exit'
alias ipscan='sudo arp-scan --interface=wlp3s0 --localnet'
alias j='jobs'
alias k='killall'
alias m='sudo make clean install'
alias n='nvim -u ~/.vimrc'
alias nf='neofetch'
alias p='python'
alias pid='echo $$'
alias record='ffmpeg -y -s 1600x900 -f x11grab -i :0.0 -r 60 out.mp4'
alias s='startx'
alias sf='screenfetch'
alias untar='tar -x -f'
alias v='vim'
alias watch='watch -c -n 0.1 -p -d'


# System Specific Aliases
# alias edwm='vim ~/Programs/dwm/config.h'
# alias ei3='vim ~/.config/i3/config'
# alias fucking='sudo'
# alias hlm2='sh /home/gavin/Documents/Games/Hotline\ Miami\ 2\ Wrong\ Number\/start.sh'
# alias hlm='sh /home/gavin/Documents/Games/Hotline\ Miami\/start.sh'
# alias mdwm='cd ~/Programs/dwm && sudo make clean install && cd ~'
# alias orange='sudo mount /dev/sdb1 ~/Orange'
# alias panes='~/Documents/Technical/Random/Color-Scripts/color-scripts/panes'
# alias sv='sh ~/Games/Stardew\ Valley\/start.sh'


# Misc
source ~/.geometry/geometry.zsh
